<?php

return [
    'common_colors' => [
        ['code' => 'black', 'name' => 'Black'],
        ['code' => 'brown', 'name' => 'Brown'],
        ['code' => 'green', 'name' => 'Green'],
        ['code' => 'orange', 'name' => 'Orange'],
        ['code' => 'white', 'name' => 'White'],
        ['code' => 'blue', 'name' => 'Blue'],
        ['code' => 'red', 'name' => 'Red'],
        ['code' => 'clay', 'name' => 'Clay'],
        ['code' => 'antique_gold', 'name' => 'Antique gold '],
        ['code' => 'banana_cream', 'name' => 'Banana cream'],
        ['code' => 'blue_jean', 'name' => 'Blue jean'],
        ['code' => 'bone', 'name' => 'Bone'],
        ['code' => 'cardinal', 'name' => 'Cardinal'],
        ['code' => 'classic_orange', 'name' => 'Classic Orange'],
        ['code' => 'cool_blue', 'name' => 'Cool Blue'],
        ['code' => 'cream', 'name' => 'Cream'],
        ['code' => 'dark_chocholate', 'name' => 'Dark chocholate'],
        ['code' => 'desert_pink', 'name' => 'Desert pink'],
        ['code' => 'forest_green', 'name' => 'Forest green'],
        ['code' => 'gold', 'name' => 'Gold'],
        ['code' => 'graphite_black', 'name' => 'Graphite black '],
        ['code' => 'heather_gray', 'name' => 'Heather gray'],
        ['code' => 'heavy_metal', 'name' => 'Heavy metal'],
        ['code' => 'indigo', 'name' => 'Indigo'],
        ['code' => 'kelly_green', 'name' => 'Kelly Green'],
        ['code' => 'light_blue', 'name' => 'Light Blue'],
        ['code' => 'light_grey', 'name' => 'Light Grey'],
        ['code' => 'light_olive', 'name' => 'Light Olive'],
        ['code' => 'light_pink', 'name' => 'Light Pink'],
        ['code' => 'maroon', 'name' => 'Maroon'],
        ['code' => 'mauve', 'name' => 'Mauve'],
        ['code' => 'midnight_navy', 'name' => 'Midnight Navy'],
        ['code' => 'military_green', 'name' => 'Military Green'],
        ['code' => 'natural', 'name' => 'Natural'],
        ['code' => 'oatmeaL', 'name' => 'OatmeaL'],
        ['code' => 'oxblood', 'name' => 'Oxblood'],
        ['code' => 'periblue', 'name' => 'Periblue'],
        ['code' => 'purple_rush', 'name' => 'Purple Rush'],
        ['code' => 'royal', 'name' => 'Royal'],
        ['code' => 'royal_pine', 'name' => 'Royal Pine'],
        ['code' => 'sand', 'name' => 'Sand'],
        ['code' => 'shiitake', 'name' => 'Shiitake'],
        ['code' => 'stonewash_denim', 'name' => 'Stonewash Denim'],
        ['code' => 'tahiti_blue', 'name' => 'Tahiti Blue'],
        ['code' => 'tan', 'name' => 'Tan'],
        ['code' => 'teal', 'name' => 'Teal'],
        ['code' => 'turquoise', 'name' => 'Turquoise'],
        ['code' => 'watermelon', 'name' => 'Watermelon'],
        ['code' => 'hot_pink', 'name' => 'Hot Pink'],
    ],

    'sizes' => ['S', 'M', 'L', 'XL', '2XL'],

    'brand_names' => [
        ['code' => 'NL', 'name' => 'Next Level'],
        ['code' => 'GD', 'name' => 'Gildan'],
        ['code' => 'CH', 'name' => 'Cotton Heritage'],
    ],

    'placeholders' => [
        'unisex_tee' => '/assets/unisex-tee.jpg',
        'long_sleeve_tee' => '/assets/long-sleeve-tee.jpg',
        'heavy_blend_hoodie' => '/assets/heavy-blend-hoodie.jpg',
        'heavyweight_hoodie' => '/assets/heavyweight-hoodie.jpg',
    ],

    'blanks' => [
        [
            'key' => 'nl-6210',
            'name' => 'Unisex Tee',
            'category' => 'TEE',
            'brandCode' => 'NL',
            'style' => '6210',
            'model' => '6210',
            'image' => '/assets/unisex-tee.jpg',
        ],
        [
            'key' => 'nl-3601',
            'name' => 'Long Sleeve Tee',
            'category' => 'LS',
            'brandCode' => 'NL',
            'style' => '3601',
            'model' => '3601',
            'image' => '/assets/long-sleeve-tee.jpg',
        ],
        [
            'key' => 'gd-18500',
            'name' => 'Heavy Blend Hoodie',
            'category' => 'HOODIE',
            'brandCode' => 'GD',
            'style' => '18500',
            'model' => '18500',
            'image' => '/assets/heavy-blend-hoodie.jpg',
        ],
        [
            'key' => 'ch-m2650ch',
            'name' => 'Heavyweight Hoodie',
            'category' => 'HOODIE',
            'brandCode' => 'CH',
            'style' => 'M2650CH',
            'model' => 'M2650CH',
            'image' => '/assets/heavyweight-hoodie.jpg',
        ],
    ],
];